/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const TaskPriority = IDL.Variant({
  'Low' : IDL.Null,
  'High' : IDL.Null,
  'Medium' : IDL.Null,
});
export const TaskCategory = IDL.Variant({
  'Work' : IDL.Null,
  'Personal' : IDL.Null,
  'Other' : IDL.Null,
});
export const Task = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'createdAt' : IDL.Int,
  'completed' : IDL.Bool,
  'dueDate' : IDL.Opt(IDL.Int),
  'category' : TaskCategory,
  'priority' : TaskPriority,
});

export const idlService = IDL.Service({
  'createTask' : IDL.Func(
      [IDL.Text, TaskPriority, TaskCategory, IDL.Opt(IDL.Int)],
      [IDL.Nat],
      [],
    ),
  'deleteTask' : IDL.Func([IDL.Nat], [], []),
  'getAllTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'getSortedTasksByDueDate' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'getTask' : IDL.Func([IDL.Nat], [Task], ['query']),
  'getTasksByCategory' : IDL.Func([TaskCategory], [IDL.Vec(Task)], ['query']),
  'getTasksByPriority' : IDL.Func([TaskPriority], [IDL.Vec(Task)], ['query']),
  'toggleTaskCompletion' : IDL.Func([IDL.Nat], [], []),
  'updateTask' : IDL.Func(
      [IDL.Nat, IDL.Text, TaskPriority, TaskCategory, IDL.Opt(IDL.Int)],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const TaskPriority = IDL.Variant({
    'Low' : IDL.Null,
    'High' : IDL.Null,
    'Medium' : IDL.Null,
  });
  const TaskCategory = IDL.Variant({
    'Work' : IDL.Null,
    'Personal' : IDL.Null,
    'Other' : IDL.Null,
  });
  const Task = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'createdAt' : IDL.Int,
    'completed' : IDL.Bool,
    'dueDate' : IDL.Opt(IDL.Int),
    'category' : TaskCategory,
    'priority' : TaskPriority,
  });
  
  return IDL.Service({
    'createTask' : IDL.Func(
        [IDL.Text, TaskPriority, TaskCategory, IDL.Opt(IDL.Int)],
        [IDL.Nat],
        [],
      ),
    'deleteTask' : IDL.Func([IDL.Nat], [], []),
    'getAllTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'getSortedTasksByDueDate' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'getTask' : IDL.Func([IDL.Nat], [Task], ['query']),
    'getTasksByCategory' : IDL.Func([TaskCategory], [IDL.Vec(Task)], ['query']),
    'getTasksByPriority' : IDL.Func([TaskPriority], [IDL.Vec(Task)], ['query']),
    'toggleTaskCompletion' : IDL.Func([IDL.Nat], [], []),
    'updateTask' : IDL.Func(
        [IDL.Nat, IDL.Text, TaskPriority, TaskCategory, IDL.Opt(IDL.Int)],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };