/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Task {
  'id' : bigint,
  'title' : string,
  'createdAt' : bigint,
  'completed' : boolean,
  'dueDate' : [] | [bigint],
  'category' : TaskCategory,
  'priority' : TaskPriority,
}
export type TaskCategory = { 'Work' : null } |
  { 'Personal' : null } |
  { 'Other' : null };
export type TaskPriority = { 'Low' : null } |
  { 'High' : null } |
  { 'Medium' : null };
export interface _SERVICE {
  'createTask' : ActorMethod<
    [string, TaskPriority, TaskCategory, [] | [bigint]],
    bigint
  >,
  'deleteTask' : ActorMethod<[bigint], undefined>,
  'getAllTasks' : ActorMethod<[], Array<Task>>,
  'getSortedTasksByDueDate' : ActorMethod<[], Array<Task>>,
  'getTask' : ActorMethod<[bigint], Task>,
  'getTasksByCategory' : ActorMethod<[TaskCategory], Array<Task>>,
  'getTasksByPriority' : ActorMethod<[TaskPriority], Array<Task>>,
  'toggleTaskCompletion' : ActorMethod<[bigint], undefined>,
  'updateTask' : ActorMethod<
    [bigint, string, TaskPriority, TaskCategory, [] | [bigint]],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];