/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Task {
    id: bigint;
    title: string;
    createdAt: bigint;
    completed: boolean;
    dueDate?: bigint;
    category: TaskCategory;
    priority: TaskPriority;
}
export enum TaskCategory {
    Work = "Work",
    Personal = "Personal",
    Other = "Other"
}
export enum TaskPriority {
    Low = "Low",
    High = "High",
    Medium = "Medium"
}
export interface backendInterface {
    createTask(title: string, priority: TaskPriority, category: TaskCategory, dueDate: bigint | null): Promise<bigint>;
    deleteTask(id: bigint): Promise<void>;
    getAllTasks(): Promise<Array<Task>>;
    getSortedTasksByDueDate(): Promise<Array<Task>>;
    getTask(id: bigint): Promise<Task>;
    getTasksByCategory(category: TaskCategory): Promise<Array<Task>>;
    getTasksByPriority(priority: TaskPriority): Promise<Array<Task>>;
    toggleTaskCompletion(id: bigint): Promise<void>;
    updateTask(id: bigint, title: string, priority: TaskPriority, category: TaskCategory, dueDate: bigint | null): Promise<void>;
}
import type { Task as _Task, TaskCategory as _TaskCategory, TaskPriority as _TaskPriority } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async createTask(arg0: string, arg1: TaskPriority, arg2: TaskCategory, arg3: bigint | null): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createTask(arg0, to_candid_TaskPriority_n1(this._uploadFile, this._downloadFile, arg1), to_candid_TaskCategory_n3(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n5(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTask(arg0, to_candid_TaskPriority_n1(this._uploadFile, this._downloadFile, arg1), to_candid_TaskCategory_n3(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n5(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async deleteTask(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTask(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTask(arg0);
            return result;
        }
    }
    async getAllTasks(): Promise<Array<Task>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTasks();
                return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTasks();
            return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSortedTasksByDueDate(): Promise<Array<Task>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSortedTasksByDueDate();
                return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSortedTasksByDueDate();
            return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTask(arg0: bigint): Promise<Task> {
        if (this.processError) {
            try {
                const result = await this.actor.getTask(arg0);
                return from_candid_Task_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTask(arg0);
            return from_candid_Task_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTasksByCategory(arg0: TaskCategory): Promise<Array<Task>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTasksByCategory(to_candid_TaskCategory_n3(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTasksByCategory(to_candid_TaskCategory_n3(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTasksByPriority(arg0: TaskPriority): Promise<Array<Task>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTasksByPriority(to_candid_TaskPriority_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTasksByPriority(to_candid_TaskPriority_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async toggleTaskCompletion(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleTaskCompletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleTaskCompletion(arg0);
            return result;
        }
    }
    async updateTask(arg0: bigint, arg1: string, arg2: TaskPriority, arg3: TaskCategory, arg4: bigint | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTask(arg0, arg1, to_candid_TaskPriority_n1(this._uploadFile, this._downloadFile, arg2), to_candid_TaskCategory_n3(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n5(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTask(arg0, arg1, to_candid_TaskPriority_n1(this._uploadFile, this._downloadFile, arg2), to_candid_TaskCategory_n3(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n5(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
}
function from_candid_TaskCategory_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TaskCategory): TaskCategory {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_TaskPriority_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TaskPriority): TaskPriority {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_Task_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Task): Task {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    createdAt: bigint;
    completed: boolean;
    dueDate: [] | [bigint];
    category: _TaskCategory;
    priority: _TaskPriority;
}): {
    id: bigint;
    title: string;
    createdAt: bigint;
    completed: boolean;
    dueDate?: bigint;
    category: TaskCategory;
    priority: TaskPriority;
} {
    return {
        id: value.id,
        title: value.title,
        createdAt: value.createdAt,
        completed: value.completed,
        dueDate: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.dueDate)),
        category: from_candid_TaskCategory_n10(_uploadFile, _downloadFile, value.category),
        priority: from_candid_TaskPriority_n12(_uploadFile, _downloadFile, value.priority)
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Work: null;
} | {
    Personal: null;
} | {
    Other: null;
}): TaskCategory {
    return "Work" in value ? TaskCategory.Work : "Personal" in value ? TaskCategory.Personal : "Other" in value ? TaskCategory.Other : value;
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Low: null;
} | {
    High: null;
} | {
    Medium: null;
}): TaskPriority {
    return "Low" in value ? TaskPriority.Low : "High" in value ? TaskPriority.High : "Medium" in value ? TaskPriority.Medium : value;
}
function from_candid_vec_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Task>): Array<Task> {
    return value.map((x)=>from_candid_Task_n7(_uploadFile, _downloadFile, x));
}
function to_candid_TaskCategory_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TaskCategory): _TaskCategory {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_TaskPriority_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TaskPriority): _TaskPriority {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TaskPriority): {
    Low: null;
} | {
    High: null;
} | {
    Medium: null;
} {
    return value == TaskPriority.Low ? {
        Low: null
    } : value == TaskPriority.High ? {
        High: null
    } : value == TaskPriority.Medium ? {
        Medium: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TaskCategory): {
    Work: null;
} | {
    Personal: null;
} | {
    Other: null;
} {
    return value == TaskCategory.Work ? {
        Work: null
    } : value == TaskCategory.Personal ? {
        Personal: null
    } : value == TaskCategory.Other ? {
        Other: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
